name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🆕 Features"
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🔧 Performance Improvements"
    labels:
      - "perf"
  - title: "🧪 Tests"
    label: "test"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "📖 Document"
    label: "docs"
  - title: "🚀 CI/CD"
    label: "ci"
  - title: "🌎 Internationalization"
    label: "translation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  <table>
    <tbody>
      <tr>
        <td rowspan="4">🪟 Windows</td>
        <td rowspan="2"><code>EXE</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-windows-amd64.zip">📥</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-windows-arm64.zip">📥</a></td>
      </tr>
      <tr>
        <td rowspan="2"><code>Portable</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-windows-amd64-portable.zip">📥</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-windows-arm64-portable.zip">📥</a></td>
      </tr>
      <tr>
        <td rowspan="3">🍎 MacOS</td>
        <td rowspan="3"><code>DMG</code></td>
        <td>universal</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-macos.dmg">📥</a></td>
      </tr>
      <tr>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-macos-amd64.dmg">📥</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-macos-arm64.dmg">📥</a></td>
      </tr>
      <tr>
        <td rowspan="6">🐧 Linux</td>
        <td><code>Flathub</code></td>
        <td>amd64</td>
        <td><a href="https://flathub.org/apps/com.gopeed.Gopeed">📥</a></td>
      </tr>
      <tr>
        <td><code>SNAP</code></td>
        <td>amd64</td>
        <td><a href="https://snapcraft.io/gopeed">📥</a></td>
      </tr>
      <tr>
        <td rowspan="2"><code>DEB</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-linux-amd64.deb">📥</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-linux-arm64.deb">📥</a></td>
      </tr>
      <tr>
        <td rowspan="2"><code>AppImage</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-linux-amd64.AppImage">📥</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-linux-arm64.AppImage">📥</a></td>
      </tr>
      <tr>
        <td rowspan="4">🤖 Android</td>
        <td rowspan="4"><code>APK</code></td>
        <td>universal</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-android.apk">📥</a></td>
      </tr>
      <tr>
        <td>armeabi-v7a</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-android-armeabi-v7a.apk">📥</a></td>
      </tr>
      <tr>
        <td>arm64-v8a</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-android-arm64-v8a.apk">📥</a></td>
      </tr>
      <tr>
        <td>x86_64</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-android-x86_64.apk">📥</a></td>
      </tr>
      <tr>
        <td>📱 iOS</td>
        <td><code>IPA</code></td>
        <td>universal</td>
        <td><a href="https://gopeed.com/api/download?tpl=Gopeed-v$RESOLVED_VERSION-ios.ipa">📥</a></td>
      </tr>
      <tr>
        <td>🐳 Docker</td>
        <td>-</td>
        <td>universal</td>
        <td><a href="https://hub.docker.com/r/liwei2633/gopeed">📥</a></td>
      </tr>
      <tr>
        <td rowspan="2">💾 Qnap</td>
        <td rowspan="2"><code>QPKG</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-v$RESOLVED_VERSION-qnap-amd64.qpkg">📥</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-v$RESOLVED_VERSION-qnap-arm64.qpkg">📥</a></td>
      </tr>
      <tr>
        <td rowspan="8">🌐 Web</td>
        <td rowspan="3"><code>Windows</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$RESOLVED_VERSION-windows-amd64.zip">📥</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$RESOLVED_VERSION-windows-arm64.zip">📥</a></td>
      </tr>
      <tr>
        <td>386</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$RESOLVED_VERSION-windows-386.zip">📥</a></td>
      </tr>
      <tr>
        <td rowspan="2"><code>MacOS</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$RESOLVED_VERSION-macos-amd64.zip">📥</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$RESOLVED_VERSION-macos-arm64.zip">📥</a></td>
      </tr>
      <tr>
        <td rowspan="3"><code>Linux</code></td>
        <td>amd64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$RESOLVED_VERSION-linux-amd64.zip">📥</a></td>
      </tr>
      <tr>
        <td>arm64</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$RESOLVED_VERSION-linux-arm64.zip">📥</a></td>
      </tr>
      <tr>
        <td>386</td>
        <td><a href="https://gopeed.com/api/download?tpl=gopeed-web-v$RESOLVED_VERSION-linux-386.zip">📥</a></td>
      </tr>
    </tbody>
  </table>

  # Release notes

  $CHANGES

  # 更新日志

  $CHANGES
