name: create release draft

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version without the v prefix"
        required: true
        default: "1.9.3"
      target_branch:
        description: "Branch or commit for the release draft"
        required: true
        default: "main"

permissions:
  contents: write
  pull-requests: read

jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Create release draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml
          commitish: ${{ github.event.inputs.target_branch }}
          version: ${{ github.event.inputs.version }}
          publish: false
          prerelease: false
